In [1]:
%load_ext autoreload
%autoreload 2
import os
import sys
os.chdir(os.path.abspath('..'))


# Metadata Checks

In [9]:
import pandas as pd
import os
benv2_root = '/data/panopticon/datasets/benv2'

fname = os.path.join(benv2_root, 'metadata.parquet')
metadata = pd.read_parquet(fname)
metadata

patch_id  \
0       S2A_MSIL2A_20170613T101031_N9999_R022_T33UUP_2...   
1       S2A_MSIL2A_20170613T101031_N9999_R022_T33UUP_2...   
2       S2A_MSIL2A_20170613T101031_N9999_R022_T33UUP_2...   
3       S2A_MSIL2A_20170613T101031_N9999_R022_T33UUP_2...   
4       S2A_MSIL2A_20170613T101031_N9999_R022_T33UUP_2...   
...                                                   ...   
480033  S2B_MSIL2A_20180525T094029_N9999_R036_T35VNL_9...   
480034  S2B_MSIL2A_20180525T094029_N9999_R036_T35VNL_9...   
480035  S2B_MSIL2A_20180525T094029_N9999_R036_T35VNL_9...   
480036  S2B_MSIL2A_20180525T094029_N9999_R036_T35VNL_9...   
480037  S2B_MSIL2A_20180525T094029_N9999_R036_T35VNL_9...   

                                                   labels  split  country  \
0       [Arable land, Broad-leaved forest, Mixed fores...   test  Austria   
1       [Arable land, Broad-leaved forest, Inland wate...   test  Austria   
2       [Arable land, Broad-leaved forest, Coniferous ...   test  Austria   
3       [Broad-leaved forest, Complex cultivation patt...   test  Austria   
4       [Broad-leaved forest, Complex cultivation patt...   test  Austria   
...                                                   ...    ...      ...   
480033  [Coniferous forest, Mixed forest, Transitional...  train  Finland   
480034                  [Coniferous forest, Mixed forest]  train  Finland   
480035                                [Coniferous forest]  train  Finland   
480036                                [Coniferous forest]  train  Finland   
480037  [Coniferous forest, Transitional woodland, shrub]  train  Finland   

                                             s1_name  \
0       S1B_IW_GRDH_1SDV_20170612T165809_33UUP_26_57   
1       S1B_IW_GRDH_1SDV_20170612T165809_33UUP_27_55   
2       S1B_IW_GRDH_1SDV_20170612T165809_33UUP_27_56   
3       S1B_IW_GRDH_1SDV_20170612T165809_33UUP_27_57   
4       S1B_IW_GRDH_1SDV_20170612T165809_33UUP_27_58   
...                                              ...   
480033  S1A_IW_GRDH_1SDV_20180525T153259_35VNL_90_86   
480034  S1A_IW_GRDH_1SDV_20180525T153259_35VNL_90_87   
480035  S1A_IW_GRDH_1SDV_20180525T153259_35VNL_90_88   
480036  S1B_IW_GRDH_1SDV_20180524T154016_35VNL_90_89   
480037  S1A_IW_GRDH_1SDV_20180525T153234_35VNL_90_90   

                               s2v1_name  contains_seasonal_snow  \
0       S2A_MSIL2A_20170613T101031_26_57                   False   
1       S2A_MSIL2A_20170613T101031_27_55                   False   
2       S2A_MSIL2A_20170613T101031_27_56                   False   
3       S2A_MSIL2A_20170613T101031_27_57                   False   
4       S2A_MSIL2A_20170613T101031_27_58                   False   
...                                  ...                     ...   
480033  S2B_MSIL2A_20180525T094029_90_86                   False   
480034  S2B_MSIL2A_20180525T094029_90_87                   False   
480035  S2B_MSIL2A_20180525T094029_90_88                   False   
480036  S2B_MSIL2A_20180525T094029_90_89                   False   
480037  S2B_MSIL2A_20180525T094029_90_90                   False   

        contains_cloud_or_shadow  
0                          False  
1                          False  
2                          False  
3                          False  
4                          False  
...                          ...  
480033                     False  
480034                     False  
480035                     False  
480036                     False  
480037                     False  

[480038 rows x 8 columns]

In [10]:
metadata['split'].value_counts()

split
train         237871
validation    122342
test          119825
Name: count, dtype: int64

In [11]:
metadata['patch_id'].iloc[1], metadata['s2v1_name'].iloc[1], metadata['s1_name'].iloc[1]

('S2A_MSIL2A_20170613T101031_N9999_R022_T33UUP_27_55',
 'S2A_MSIL2A_20170613T101031_27_55',
 'S1B_IW_GRDH_1SDV_20170612T165809_33UUP_27_55')

In [17]:
s1_path = 'BigEarthNet-S1'
s2_path = 'BigEarthNet-S2'

tile_id = '_'.join(metadata['patch_id'].iloc[0].split('_')[:-2])
s1_tile_id = '_'.join(metadata['s1_name'].iloc[0].split('_')[:-3])
patch_id = metadata['patch_id'].iloc[0]
s1_name = metadata['s1_name'].iloc[0]

file_name = metadata['s1_name'].iloc[0] + '_VV.tif'
s1 = os.path.join(benv2_root, s1_path, s1_tile_id, s1_name, file_name)

print(s1)
print(os.path.exists(s1))

file_name = metadata['patch_id'].iloc[0] + '_B01.tif'
print(patch_id)

s2 = os.path.join(benv2_root, s2_path, tile_id, patch_id, file_name)
print(s2)
os.path.exists(s2)

/data/panopticon/datasets/benv2/BigEarthNet-S1/S1B_IW_GRDH_1SDV_20170612T165809/S1B_IW_GRDH_1SDV_20170612T165809_33UUP_26_57/S1B_IW_GRDH_1SDV_20170612T165809_33UUP_26_57_VV.tif
True
S2A_MSIL2A_20170613T101031_N9999_R022_T33UUP_26_57
/data/panopticon/datasets/benv2/BigEarthNet-S2/S2A_MSIL2A_20170613T101031_N9999_R022_T33UUP/S2A_MSIL2A_20170613T101031_N9999_R022_T33UUP_26_57/S2A_MSIL2A_20170613T101031_N9999_R022_T33UUP_26_57_B01.tif


True

# Dataset Checks

## Multimodal mode: Train

In [18]:
from dinov2.data.datasets.benv2 import BigEarthNetv2Wrapper
benv2_root = '/data/panopticon/datasets/benv2'

ben_train = BigEarthNetv2Wrapper(benv2_root, normalize=True, multimodal=True, full_spectra=True)
ben_train.chn_ids, len(ben_train)

({'ben-s1': tensor([-1., -2.]),
  'ben-s2': tensor([ 442.7530,  492.7146,  559.8556,  664.6184,  704.1148,  740.4922,
           782.7339,  832.7195,  864.7394,  945.0536, 1613.6824, 2202.3992])},
 237871)

In [12]:
ben_train.metadata

patch_id  \
0       S2A_MSIL2A_20170613T101031_N9999_R022_T33UUP_3...   
1       S2A_MSIL2A_20170613T101031_N9999_R022_T33UUP_3...   
2       S2A_MSIL2A_20170613T101031_N9999_R022_T33UUP_3...   
3       S2A_MSIL2A_20170613T101031_N9999_R022_T33UUP_3...   
4       S2A_MSIL2A_20170613T101031_N9999_R022_T33UUP_3...   
...                                                   ...   
237866  S2B_MSIL2A_20180525T094029_N9999_R036_T35VNL_9...   
237867  S2B_MSIL2A_20180525T094029_N9999_R036_T35VNL_9...   
237868  S2B_MSIL2A_20180525T094029_N9999_R036_T35VNL_9...   
237869  S2B_MSIL2A_20180525T094029_N9999_R036_T35VNL_9...   
237870  S2B_MSIL2A_20180525T094029_N9999_R036_T35VNL_9...   

                                                   labels  split  country  \
0       [Broad-leaved forest, Coniferous forest, Inlan...  train  Austria   
1       [Broad-leaved forest, Coniferous forest, Mixed...  train  Austria   
2       [Broad-leaved forest, Coniferous forest, Mixed...  train  Austria   
3       [Arable land, Broad-leaved forest, Inland wate...  train  Austria   
4       [Coniferous forest, Mixed forest, Pastures, Ur...  train  Austria   
...                                                   ...    ...      ...   
237866  [Coniferous forest, Mixed forest, Transitional...  train  Finland   
237867                  [Coniferous forest, Mixed forest]  train  Finland   
237868                                [Coniferous forest]  train  Finland   
237869                                [Coniferous forest]  train  Finland   
237870  [Coniferous forest, Transitional woodland, shrub]  train  Finland   

                                             s1_name  \
0       S1B_IW_GRDH_1SDV_20170612T165809_33UUP_37_88   
1       S1B_IW_GRDH_1SDV_20170612T165809_33UUP_37_89   
2       S1B_IW_GRDH_1SDV_20170612T165809_33UUP_37_90   
3       S1B_IW_GRDH_1SDV_20170612T165809_33UUP_38_88   
4       S1B_IW_GRDH_1SDV_20170612T165809_33UUP_38_89   
...                                              ...   
237866  S1A_IW_GRDH_1SDV_20180525T153259_35VNL_90_86   
237867  S1A_IW_GRDH_1SDV_20180525T153259_35VNL_90_87   
237868  S1A_IW_GRDH_1SDV_20180525T153259_35VNL_90_88   
237869  S1B_IW_GRDH_1SDV_20180524T154016_35VNL_90_89   
237870  S1A_IW_GRDH_1SDV_20180525T153234_35VNL_90_90   

                               s2v1_name  contains_seasonal_snow  \
0       S2A_MSIL2A_20170613T101031_37_88                   False   
1       S2A_MSIL2A_20170613T101031_37_89                   False   
2       S2A_MSIL2A_20170613T101031_37_90                   False   
3       S2A_MSIL2A_20170613T101031_38_88                   False   
4       S2A_MSIL2A_20170613T101031_38_89                   False   
...                                  ...                     ...   
237866  S2B_MSIL2A_20180525T094029_90_86                   False   
237867  S2B_MSIL2A_20180525T094029_90_87                   False   
237868  S2B_MSIL2A_20180525T094029_90_88                   False   
237869  S2B_MSIL2A_20180525T094029_90_89                   False   
237870  S2B_MSIL2A_20180525T094029_90_90                   False   

        contains_cloud_or_shadow  
0                          False  
1                          False  
2                          False  
3                          False  
4                          False  
...                          ...  
237866                     False  
237867                     False  
237868                     False  
237869                     False  
237870                     False  

[237871 rows x 8 columns]

In [20]:
import random

for i in range(100):
    idx = random.randint(0, len(ben_train)-1)
    out, label = ben_train[idx]
    print(idx, out['imgs'][0].shape, out['imgs'][1].shape, out['chn_ids'][0].shape, out['chn_ids'][1].shape, label)



131495 torch.Size([2, 120, 120]) torch.Size([12, 120, 120]) torch.Size([2]) torch.Size([12]) tensor([0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0])
137290 torch.Size([2, 120, 120]) torch.Size([12, 120, 120]) torch.Size([2]) torch.Size([12]) tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1])
156103 torch.Size([2, 120, 120]) torch.Size([12, 120, 120]) torch.Size([2]) torch.Size([12]) tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1])
48231 torch.Size([2, 120, 120]) torch.Size([12, 120, 120]) torch.Size([2]) torch.Size([12]) tensor([0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0])
53959 torch.Size([2, 120, 120]) torch.Size([12, 120, 120]) torch.Size([2]) torch.Size([12]) tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1])
222446 torch.Size([2, 120, 120]) torch.Size([12, 120, 120]) torch.Size([2]) torch.Size([12]) tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1])
21014 torch.Size([2, 120, 120]) torch.Size([12, 

### Val and Test

In [22]:
from dinov2.data.datasets.benv2 import BigEarthNetv2Wrapper
benv2_root = '/data/panopticon/datasets/benv2'

ben_val = BigEarthNetv2Wrapper(benv2_root, normalize=True, multimodal=False, split='validation', full_spectra=True)
ben_val.chn_ids, len(ben_val)

/home/ando/PanOpticOn/dinov2/data/datasets/benv2.py:617: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  self.chn_ids = torch.tensor(extract_wavemus(load_ds_cfg(self.ds_name), return_sigmas=full_spectra), dtype=torch.long)


(tensor([[  -1,   -1],
         [  -2,   -1],
         [ 442,   42],
         [ 492,   42],
         [ 559,   23],
         [ 664,   20],
         [ 704,    9],
         [ 740,    9],
         [ 782,   13],
         [ 832,   70],
         [ 864,   14],
         [ 945,   13],
         [1613,   60],
         [2202,  115]]),
 122342)

In [25]:
sample, label = ben_val[55]
chn_ids = sample['chn_ids']
chn_ids.shape, sample['imgs'].shape
# sample['imgs'][0].min(), sample['imgs'][0].max(), sample['imgs'][1].min(), sample['imgs'][1].max()

(torch.Size([14, 2]), torch.Size([14, 120, 120]))

In [26]:
chn_ids[:,0], chn_ids[:,1]

(tensor([  -1,   -2,  442,  492,  559,  664,  704,  740,  782,  832,  864,  945,
         1613, 2202]),
 tensor([ -1,  -1,  42,  42,  23,  20,   9,   9,  13,  70,  14,  13,  60, 115]))

In [27]:
for i in range(1000):
    idx = random.randint(0, len(ben_val)-1)
    out, label = ben_val[idx]
    print(idx, out['imgs'].shape, out['chn_ids'].shape, label)


41182 torch.Size([14, 120, 120]) torch.Size([14, 2]) tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1])
56051 torch.Size([14, 120, 120]) torch.Size([14, 2]) tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1])
73012 torch.Size([14, 120, 120]) torch.Size([14, 2]) tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0])
17687 torch.Size([14, 120, 120]) torch.Size([14, 2]) tensor([0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0])
26940 torch.Size([14, 120, 120]) torch.Size([14, 2]) tensor([0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0])
103408 torch.Size([14, 120, 120]) torch.Size([14, 2]) tensor([0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
114113 torch.Size([14, 120, 120]) torch.Size([14, 2]) tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1])
94298 torch.Size([14, 120, 120]) torch.Size([14, 2]) tensor([0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0])
84284 torch.Size([14, 120, 120]) torch.Size([1

In [29]:
ben_test = BigEarthNetv2Wrapper(benv2_root, normalize=True, multimodal=False, split='test', full_spectra=True)
ben_test.chn_ids, len(ben_test)

/home/ando/PanOpticOn/dinov2/data/datasets/benv2.py:617: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  self.chn_ids = torch.tensor(extract_wavemus(load_ds_cfg(self.ds_name), return_sigmas=full_spectra), dtype=torch.long)


(tensor([[  -1,   -1],
         [  -2,   -1],
         [ 442,   42],
         [ 492,   42],
         [ 559,   23],
         [ 664,   20],
         [ 704,    9],
         [ 740,    9],
         [ 782,   13],
         [ 832,   70],
         [ 864,   14],
         [ 945,   13],
         [1613,   60],
         [2202,  115]]),
 119825)

In [31]:
for i in range(100):
    idx = random.randint(0, len(ben_test)-1)
    out, label = ben_test[idx]
    print(idx, out['imgs'].shape, out['chn_ids'].shape, label)


74802 torch.Size([14, 120, 120]) torch.Size([14, 2]) tensor([0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
91136 torch.Size([14, 120, 120]) torch.Size([14, 2]) tensor([0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
31233 torch.Size([14, 120, 120]) torch.Size([14, 2]) tensor([0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0])
47105 torch.Size([14, 120, 120]) torch.Size([14, 2]) tensor([0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
10112 torch.Size([14, 120, 120]) torch.Size([14, 2]) tensor([0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
83424 torch.Size([14, 120, 120]) torch.Size([14, 2]) tensor([1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0])
45909 torch.Size([14, 120, 120]) torch.Size([14, 2]) tensor([1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0])


80569 torch.Size([14, 120, 120]) torch.Size([14, 2]) tensor([0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0])
8050 torch.Size([14, 120, 120]) torch.Size([14, 2]) tensor([0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0])
107556 torch.Size([14, 120, 120]) torch.Size([14, 2]) tensor([0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
66793 torch.Size([14, 120, 120]) torch.Size([14, 2]) tensor([0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0])
39734 torch.Size([14, 120, 120]) torch.Size([14, 2]) tensor([0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0])
104160 torch.Size([14, 120, 120]) torch.Size([14, 2]) tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1])
118818 torch.Size([14, 120, 120]) torch.Size([14, 2]) tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0])
63812 torch.Size([14, 120, 120]) torch.Size([14, 2]) tensor([0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
84132 torch.Size([14, 120, 120]) torch.Size([1

## Unimodal mode

In [37]:
from dinov2.data.datasets.benv2 import BigEarthNetv2Wrapper
benv2_root = '/data/panopticon/datasets/benv2'

ben = BigEarthNetv2Wrapper(benv2_root, normalize=True, multimodal=True, full_spectra=True)


In [38]:
ben.chn_ids

{'ben-s1': tensor([[-1., -1.],
         [-2., -1.]]),
 'ben-s2': tensor([[ 442.7530,   42.5272],
         [ 492.7146,   42.5272],
         [ 559.8556,   23.1510],
         [ 664.6184,   20.7967],
         [ 704.1148,    9.6195],
         [ 740.4922,    9.3563],
         [ 782.7339,   13.1001],
         [ 832.7195,   70.4731],
         [ 864.7394,   14.4033],
         [ 945.0536,   13.4182],
         [1613.6824,   60.9985],
         [2202.3992,  115.9262]])}

In [39]:
data, label = ben[-250]

data['imgs'][0].shape, data['imgs'][1].shape, data['chn_ids'], label

(torch.Size([2, 120, 120]),
 torch.Size([12, 120, 120]),
 [tensor([[-1., -1.],
          [-2., -1.]]),
  tensor([[ 442.7530,   42.5272],
          [ 492.7146,   42.5272],
          [ 559.8556,   23.1510],
          [ 664.6184,   20.7967],
          [ 704.1148,    9.6195],
          [ 740.4922,    9.3563],
          [ 782.7339,   13.1001],
          [ 832.7195,   70.4731],
          [ 864.7394,   14.4033],
          [ 945.0536,   13.4182],
          [1613.6824,   60.9985],
          [2202.3992,  115.9262]])],
 tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0]))

In [40]:
import random
for i in range(100):
    idx = random.randint(0, len(ben)-1)
    out, label = ben[idx]
    print(idx, out['imgs'][0].shape, out['imgs'][1].shape, out['chn_ids'][0].shape, out['chn_ids'][1].shape, label)


210409 torch.Size([2, 120, 120]) torch.Size([12, 120, 120]) torch.Size([2, 2]) torch.Size([12, 2]) tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0])
81232 torch.Size([2, 120, 120]) torch.Size([12, 120, 120]) torch.Size([2, 2]) torch.Size([12, 2]) tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0])
135331 torch.Size([2, 120, 120]) torch.Size([12, 120, 120]) torch.Size([2, 2]) torch.Size([12, 2]) tensor([0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0])
67073 torch.Size([2, 120, 120]) torch.Size([12, 120, 120]) torch.Size([2, 2]) torch.Size([12, 2]) tensor([0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
203056 torch.Size([2, 120, 120]) torch.Size([12, 120, 120]) torch.Size([2, 2]) torch.Size([12, 2]) tensor([0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0])
139236 torch.Size([2, 120, 120]) torch.Size([12, 120, 120]) torch.Size([2, 2]) torch.Size([12, 2]) tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0])


159681 torch.Size([2, 120, 120]) torch.Size([12, 120, 120]) torch.Size([2, 2]) torch.Size([12, 2]) tensor([0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0])
180481 torch.Size([2, 120, 120]) torch.Size([12, 120, 120]) torch.Size([2, 2]) torch.Size([12, 2]) tensor([1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
206490 torch.Size([2, 120, 120]) torch.Size([12, 120, 120]) torch.Size([2, 2]) torch.Size([12, 2]) tensor([0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0])
102437 torch.Size([2, 120, 120]) torch.Size([12, 120, 120]) torch.Size([2, 2]) torch.Size([12, 2]) tensor([0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0])
237181 torch.Size([2, 120, 120]) torch.Size([12, 120, 120]) torch.Size([2, 2]) torch.Size([12, 2]) tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0])
21384 torch.Size([2, 120, 120]) torch.Size([12, 120, 120]) torch.Size([2, 2]) torch.Size([12, 2]) tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1])
130830 torc

In [42]:
out['imgs'][0].max(), out['imgs'][0].min()

(tensor(2.2682), tensor(-2.4412))